name: Process GitHub User Removals

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode (no actual removals)'
        type: boolean
        default: true
      usernames:
        description: 'JSON array of GitHub usernames to remove'
        type: string
        required: false

  repository_dispatch:
    types: [remove_github_users]

permissions:
  contents: read

jobs:
  remove-users-from-cdcgov:
    runs-on: ubuntu-latest
    outputs:
      completion_status: ${{ steps.set-outputs.outputs.completion_status }}
      processed_usernames: ${{ steps.set-outputs.outputs.processed_usernames }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debug Event Information
        run: |
          echo "=== Event Information ==="
          echo "Event name: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "Event type: ${{ github.event.action }}"
            echo "Payload: ${{ toJSON(github.event.client_payload) }}"
            echo "Test mode: ${{ github.event.client_payload.test_mode }}"
            echo "Usernames: ${{ toJSON(github.event.client_payload.usernames) }}"
            echo "Callback repo: ${{ github.event.client_payload.callback_repo }}"
            echo "Callback event: ${{ github.event.client_payload.callback_event }}"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Test mode: ${{ inputs.test_mode }}"
            echo "Usernames: ${{ inputs.usernames }}"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate GitHub App Token for CDCGov
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GIT_APP_ONBOARD_OFFBOARD_APP_ID }}
          private-key: ${{ secrets.GIT_APP_ONBOARD_OFFBOARD_PRIVATE_KEY }}
          owner: cdcgov

      - name: Set test mode and usernames
        id: params
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "TEST_MODE=${{ github.event.client_payload.test_mode }}" >> $GITHUB_ENV

            # Convert the JSON array to a properly formatted single-line string without quotes around it
            FORMATTED_JSON=$(echo '${{ toJSON(github.event.client_payload.usernames) }}' | tr -d '\n')
            echo "USERNAMES_JSON=${FORMATTED_JSON}" >> $GITHUB_ENV

            # Set callback info if provided
            if [ -n "${{ github.event.client_payload.callback_repo }}" ]; then
              echo "CALLBACK_REPO=${{ github.event.client_payload.callback_repo }}" >> $GITHUB_ENV
            fi
            if [ -n "${{ github.event.client_payload.callback_event }}" ]; then
              echo "CALLBACK_EVENT=${{ github.event.client_payload.callback_event }}" >> $GITHUB_ENV
            fi

          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TEST_MODE=${{ inputs.test_mode }}" >> $GITHUB_ENV

            # Use provided usernames or empty array if not provided
            if [ -n "${{ inputs.usernames }}" ]; then
              echo "USERNAMES_JSON=${{ inputs.usernames }}" >> $GITHUB_ENV
            else
              echo "USERNAMES_JSON=[]" >> $GITHUB_ENV
            fi
          fi

      - name: Execute User Removal Script
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CALLBACK_TOKEN: ${{ secrets.CDCGOV_REPO_PAT }}
          TEST_MODE: ${{ env.TEST_MODE }}
          USERNAMES_JSON: ${{ env.USERNAMES_JSON }}
          CALLBACK_REPO: ${{ env.CALLBACK_REPO }}
          CALLBACK_EVENT: ${{ env.CALLBACK_EVENT }}
        run: |
          export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${PWD}/scripts"
          python scripts/main.py

      - name: Set outputs for callback
        id: set-outputs
        run: |
          echo "completion_status=${{ job.status }}" >> $GITHUB_OUTPUT
          echo "processed_usernames=${{ env.USERNAMES_JSON }}" >> $GITHUB_OUTPUT

      - name: Upload removal logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: removal-logs
          path: |
            github_removal_*.log
            removal_results.json

  send-completion-callback:
    needs: remove-users-from-cdcgov
    if: |
      always() &&
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.callback_repo != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Send completion callback
        env:
          CALLBACK_TOKEN: ${{ secrets.CDCGOV_REPO_PAT }}
        run: |
          export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${PWD}/scripts"
          python scripts/send_callback.py \
            "${{ needs.remove-users-from-cdcgov.outputs.completion_status }}" \
            "${{ github.event.client_payload.test_mode }}" \
            "${{ needs.remove-users-from-cdcgov.outputs.processed_usernames }}"
